version: 2.1
jobs:
  verify:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Clean
          command: mvn clean
      - run:
          name: Verify
          command: mvn verify

      - store_test_results:
          path: target/surefire-reports/junitreports

workflows:
  commit:
    jobs:
      - verify